// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZKnlCzo-PpSEE9aHkIarX6R07tKBNqo',
    appId: '1:179409311322:web:9853e1829ad7a22d46aa63',
    messagingSenderId: '179409311322',
    projectId: 'mylogs-flutter',
    authDomain: 'mylogs-flutter.firebaseapp.com',
    storageBucket: 'mylogs-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBufH9b7pBKhBIZfkHjWtwwZi7_HCoocQY',
    appId: '1:179409311322:android:d75c0746e872736f46aa63',
    messagingSenderId: '179409311322',
    projectId: 'mylogs-flutter',
    storageBucket: 'mylogs-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDtJ-MI9YDBARylMvKQCdIwcw6QPlYdI',
    appId: '1:179409311322:ios:005351ca4c70074746aa63',
    messagingSenderId: '179409311322',
    projectId: 'mylogs-flutter',
    storageBucket: 'mylogs-flutter.appspot.com',
    iosBundleId: 'edu.nutech.mylogs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtDtJ-MI9YDBARylMvKQCdIwcw6QPlYdI',
    appId: '1:179409311322:ios:005351ca4c70074746aa63',
    messagingSenderId: '179409311322',
    projectId: 'mylogs-flutter',
    storageBucket: 'mylogs-flutter.appspot.com',
    iosBundleId: 'edu.nutech.mylogs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoZKnlCzo-PpSEE9aHkIarX6R07tKBNqo',
    appId: '1:179409311322:web:f3a925c84717e79546aa63',
    messagingSenderId: '179409311322',
    projectId: 'mylogs-flutter',
    authDomain: 'mylogs-flutter.firebaseapp.com',
    storageBucket: 'mylogs-flutter.appspot.com',
  );
}
